### ISSUE TITLE
When will the dataset stop maintenance?

### ISSUE THREAD

**Issue by JiahuiFeng** [fangli80/doc-PPARgene#1]
Hi，Li Fang,
I have been waiting for dataset maintenance for several weeks. It said it would be back before 3/15/2019. But it is still in maintenance. I wonder how long it will take or do you have other solutions that I can get access to the data？

Thank U！
Best！
Jiahui Feng

**Comment by fangli80** [comment]
Hi Jiahua, 
I'm sorry for the delay. The list of verified and predicted target genes can be downloaded from here:

[PPAR alpha target genes.xlsx](https://github.com/fangli08/doc-PPARgene/files/2985414/PPAR.alpha.target.genes.xlsx)
[PPAR delta target genes.xlsx](https://github.com/fangli08/doc-PPARgene/files/2985415/PPAR.delta.target.genes.xlsx)
[PPAR gamma target genes.xlsx](https://github.com/fangli08/doc-PPARgene/files/2985416/PPAR.gamma.target.genes.xlsx)
[Predicted PPAR target genes.xlsx](https://github.com/fangli08/doc-PPARgene/files/2985417/Predicted.PPAR.target.genes.xlsx)

The full service of the website will be back soon. 
Thank you for using PPARgene database. 

Best,
Li

**Comment by fangli80** [comment]
Hi Hi Jiahua, 

The full service is back. Please visit http://www.ppargene.org/

Best, 
Li
